### ISSUE TITLE
map

### ISSUE THREAD

**Issue by MinhKMA** [becksteadn/Mapper-Server#1]
hello becksteadn, could you please share me two files (marker_map.html and heatmap.html)?

**Comment by scriptingislife** [comment]
Hi,

The HTML files are hosted at the links below. My live version of the project is hosted at https://rootonyour.webcam

If you're interested in getting this up and running I can work on writing a better guide. Most of the README.md was documentation for myself.

[Heatmap](https://rootonyour.webcam/res/html/maps/heatmap.html)

[Markers](https://rootonyour.webcam/res/html/maps/markers.html)

**Comment by MinhKMA** [comment]
hi, 
Could you work on writing a better guide? I like your project very much and I want to learn it .
