### ISSUE TITLE
typo Line 12 in docker-compose file

### ISSUE THREAD

**Issue by congto** [becksteadn/Mapper-Server#4]
Hi

You have a error typo, you need to fix in line 12.

https://github.com/becksteadn/Mapper-Server/blob/09007aeda2a49336eaa6d9fa03111ff79620bc2d/docker-compose.yml#L12

**Comment by scriptingislife** [comment]
Yep I saw it right after. Fixed in https://github.com/becksteadn/Mapper-Server/commit/2fe789dee2b122b47a107159bd1aa2ad4fe10c83
